package com.aman.taxcalculator.ga555a.domain.model


data class Ga55aData(
    val name:String,
    val pan:String,
    val tan:String,
    val bankAccount:String,
    val post:String,
    val siNo:String,
    val gpfNo:String,
    val mobileNo:String,

    val month:String,
    val basicPay:String,
    val dearnessPay:String,
    val leavePay:String,
    val splPay:String,
    val da:String,
    val hra:String,
    val washingAllowance:String,
    val rpo:String,
    val otherAllowance1:String,
    val otherAllowance2:String,
    val grossPay:String,
    val gpf:String,
    val gpfLoan:String,
    val si:String,
    val siLoanAndInt:String,
    val rghs:String,
    val lic:String,
    val groupInsuranceAccidental:String,
    val incomeTaxOrTds:String,
    val benefactorFund:String,
    val cmCoronaRelief:String,
    val otherDeduction1:String,
    val otherDeduction2:String,
    val totalDeduction:String,
    val netPayment:String,

)

//val month:String,
//val basicPay:String,
//val dearnessPay:String,
//val leavePay:String,
//val splPay:String,
//val da:String,
//val hra:String,
//val washingAllowance:String,
//val rpo:String,
//val otherAllowance1:String,
//val otherAllowance2:String,
//val grossPay:String,
//val gpf:String,
//val gpfLoan:String,
//val si:String,
//val siLoanAndInt:String,
//val rghs:String,
//val lic:String,
//val groupInsuranceAccidental:String,
//val incomeTaxOrTds:String,
//val benefactorFund:String,
//val cmCoronaRelief:String,
//val otherDeduction1:String,
//val otherDeduction2:String,
//val totalDeduction:String,
//val netPayment:String,